config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  resources :students
  root 'students#index'
  get '/get_student_by_user' => 'students#get_student_by_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

	validates_presence_of :name, :student_class, :phone, :address
	validates :phone, uniqueness: true, numericality: true
	validates_length_of :phone, minimum: 10, maximum: 10
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  before_create :set_default_role
  has_many :students,  dependent: :destroy

  def set_default_role
    self.role ||= "user"
  end
 
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
     :recoverable, :rememberable, :validatable,:omniauthable, :omniauth_providers => [:google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def admin?
    if role == "admin"
      return true
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	protect_from_forgery
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

	#google callbacks
  def google_oauth2

    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
    	sign_in_and_redirect @user,  notice: "User Sign In Successfully"
    else
    	redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @current_user||=  current_user
    if current_user.admin?
      @users= User.all - [current_user]
      render template: 'students/admin'#,:locals => { :users => @users}
    else
      @students = current_user.students
    end
    @student = Student.new
    respond_to do |format|
      format.json {render json: { data: @students}}
      format.html
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @current_user = @student.user
    respond_to do |format|
      format.json {render json: { data: @student}}
      format.html
      format.js
    end
  end

  def get_student_by_user
    @user = User.find(params[:user_id])
    @students = @user.students
    respond_to do |format|
      #format.json {render json: { data: @student}}
      format.html
      format.js
    end
  end
  # POST /students
  # POST /students.json
  def create
    current_user = User.find(params[:student][:user_id])
    @student = current_user.students.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        # format.json { render :show, status: :created, location: @student }
        format.json {render :json => {:status => 'success'}}
        format.js
      else
        format.html { render :new }
        format.json {render :json => {:status => 'false', errors: @student.errors.full_messages}}
        # format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json {render :json => {:status => 'success'}}
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json {render :json => {:status => 'success'}}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :student_class, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def format_date(date)
		date.strftime("%m/%d/%Y")
	end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_flash.html.erb
<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

<script type="text/javascript">
  setTimeout(function(){
    $('.alert').fadeOut();
   }, 10000);
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- Button -->
    <% if user_signed_in? %>
      <div class="navbar-header">
        Logged in as: <strong><%= current_user.email %></strong>.
      </div>
      <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-default navbar-btn navbar-right'  %>

    <% else %>
      <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
      <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>
</nav>

app/views/layouts/_load_js_and_css.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="/assets/jquery.validate.min.js"></script>

<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>

<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>


<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="//cdn.datatables.net/plug-ins/1.10.12/sorting/datetime-moment.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.10.21/dataRender/datetime.js"></script>

<script src="/assets/animsition/js/animsition.min.js"></script>
<script src="/assets/bootstrap/js/popper.js"></script>
<script src="/assets/bootstrap/js/bootstrap.min.js"></script>
<script src="/assets/select2/select2.min.js"></script>

<link rel="stylesheet" type="text/css" href="/assets/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/assets/font-awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/assets/animate/animate.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css">

<link rel="stylesheet" type="text/css" href="/assets/animsition/css/animsition.min.css">
<link rel="stylesheet" type="text/css" href="/assets/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="/assets/util.css">
<link rel="stylesheet" type="text/css" href="/assets/main.css">
<link rel="stylesheet" type="text/css" href="/assets/custom.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studentproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/load_js_and_css' %>
  </head>

  <body>
    <div class="container">
    <%= render 'layouts/flash' %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </div>
  </body>
</html>



  

app/views/students/_add_student_form_modal.html.erb
<div class="modal fade" id="add_student_form_modal_header" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <% @student||= student %>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
        <%= render 'student_update_form', student: @student %>
      </div><br>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $(".delete_student_record").click(function (){
      var id = $("#student_id").val();
      $.ajax({
        type: "delete",
        url : "/students/" +id+ ".json",
        success: function(data)
        {
          if (data["status"] == "false"){
            $('.notice').fadeIn().html($('<p class="alert alert-danger"> '+data.errors[0]+'</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
            $("#add_student_form_modal_header").modal('hide')
          }else{
            $("#add_student_form_modal_header").modal('hide')
            $('.notice').fadeIn().html($('<p class="alert alert-danger">Student was successfully Deleted.</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
            $('#student_table').DataTable().ajax.reload();
          }
        },
        error: function(data){
          $('.notice').fadeIn().html($('<p class="alert alert-danger">Something Went Wrong While Saving New Student Record.</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
        }
      }); //ajax end
    }); //function end
 }); //main function end
</script>

app/views/students/_form.html.erb
<p class="notice"></p>
<!-- <p class="error"></p> -->
<label style="text-align: center;width: 924px;font-family: monospace;font-size: xx-large;margin-top: 45px;">Student Records</label>
<!-- Form start -->

<%= form_with(model: student, local: true, class: "form-horizontal", id: "loginForm", remote: true) do |form| %>
  <%= form.hidden_field :user_id, :value => @current_user.id %>
  <%#= form.hidden_field :id, :value => student.id %>
  <div class="row set_row_width">
    <div class="col-25">
      <label for="fname" class="cutom_css">Student Name</label>
    </div>
    <div class="col-75">
      <%= form.text_field :name , placeholder: "Jhoe Doye" ,required: true%>
    </div>
  </div>
  <div class="row set_row_width">
    <div class="col-25">
      <label for="fname" class="cutom_css">Student Class</label>
    </div>
    <div class="col-75">
      <%= form.text_field :student_class , placeholder: "Class X" ,required: true%>
    </div>
  </div>
  <div class="row set_row_width" >
    <div class="col-25">
      <label for="fname" class="cutom_css">Student Address</label>
    </div>
    <div class="col-75 has-error">
      <%= form.text_area :address , placeholder: "XYZ, Delhi 110049", class: "form-control" ,required: true%>
    </div>
  </div>
  <div class="row set_row_width">
    <div class="col-25" >
      <label for="fname" class="cutom_css">Student Phone</label>
    </div>
    <div class="col-75">
      <%= form.text_field :phone , placeholder: "9990625846", required: true %>
    </div>
  </div>
  <div class="pull-right form_button">
    <%= form.button "Submit" ,class: "btn btn-danger btn-lg btn-block" %>
  </div>
<% end %><!-- Form end -->

app/views/students/_student_records.html.erb
<% @students ||= students %>
<!-- Table Start-->
<table id="student_table" data-source="<%= students_path(format: :json) %>", style="width:100" class="table">
  <thead>
    <tr class="table-head">
      <th></th>
      <th>Student ID</th>
      <th>Date</th>
      <th>Name</th>
      <th>Student Class</th>
      <th>Phone</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr class="find-selected-checkbox">
        <td></td><!--<input type="checkbox" class="checkbox"> -->
        <td><%= student.id%></td>
        <td><%= format_date(student.created_at)%></td>
        <td><%= student.name %></td>
        <td><%= student.student_class %></td>
        <td><%= student.phone %></td>
        <td><%= student.address %></td>
      </tr>
    <% end %>
  </tbody>
</table><!-- Table End-->

app/views/students/_student_update_form.html.erb
<%= form_with(model: @student, local: true, class: "form-horizontal", class: "student-form", remote: true) do |form| %>
  <%= form.hidden_field :user_id, :value => @current_user.id %>
  <%= form.hidden_field :id, :value => @student.id %>
  <div class="row set_row_width">
    <div class="col-25">
      <label for="fname" class="cutom_css">Student Name</label>
    </div>
    <div class="col-75">
      <%= form.text_field :name , placeholder: "Jhoe Doye" ,required: true%>
    </div>
  </div>
  <div class="row set_row_width">
    <div class="col-25">
      <label for="fname" class="cutom_css">Student Class</label>
    </div>
    <div class="col-75">
      <%= form.text_field :student_class , placeholder: "Class X" ,required: true%>
    </div>
  </div>
  <div class="row set_row_width" >
    <div class="col-25">
      <label for="fname" class="cutom_css">Student Address</label>
    </div>
    <div class="col-75 has-error">
      <%= form.text_area :address , placeholder: "XYZ, Delhi 110049", class: "form-control" ,required: true%>
    </div>
  </div>
  <div class="row set_row_width">
    <div class="col-25" >
      <label for="fname" class="cutom_css">Student Phone</label>
    </div>
    <div class="col-75">
      <%= form.text_field :phone , placeholder: "9990625846", required: true %>
    </div>
  </div><br>
  <div class="row">
    <input type="hidden" id="ss_id" name="ss_id" value="<%= @student.id %>">
    <input class="btn btn-danger btn-lg col-sm-4 delete_student_record" type="button" value="Delete Record"></input>
    <button type="submit" class="btn btn-primary btn-lg col-sm-4 rrupdate_student_record">Edit Record</button>
  </div>

<% end %><!-- Form end -->

<script type="text/javascript">
  $(function() {
    $(".student-form").validate({
      // errorClass: "validate_error",
      rules:{
        'student[phone]':{
          digits: true,
          minlength:10,
          maxlength:10,
        }
      },
      messages:{
        'student[phone]':"Invalid Mobile Number"
      },
      submitHandler: function(form) {
        var id = $("#student_id").val();
        $.ajax({
          type: "put",
          url : "/students/" +id+ ".json",
          data: $(".student-form").serialize(), // serializes the form's elements.
          success: function(data)
          {
            $("#add_student_form_modal_header").modal('hide')
            if (data["status"] == "false"){
              $('.notice').fadeIn().html($('<p class="alert alert-danger"> '+data.errors[0]+'</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
            }else{
              $('.notice').fadeIn().html($('<p class="alert alert-success">Student was successfully Updated.</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
              $('#student_table').DataTable().ajax.reload();
            }
          },
          error: function(data){
            $('.notice').fadeIn().html($('<p class="alert alert-danger">Something Went Wrong While Saving New Student Record.</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
          }
        }); //ajax close
      } //submit handler close
    }); //form close
  }); //main function close
</script>

app/views/students/_user_details.html.erb
<div style="text-align: center;">
  <label style="font-family: monospace;font-size: xx-large;">Super Admin</label><br>
  <label style="font-family: monospace;font-size: xx-large;">Signed up Users</label><br>
</div>
<table id="user_table" data-source="<%= students_path(format: :json) %>", style="width:100" class="table">
  <thead>
    <tr class="table-head">
      <th>Users</th>
      <th>Date</th>
      <th>Name</th>
      <th>Login Email</th>
      <th>View Students</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id%></td>
        <td><%= format_date(user.created_at) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><% user.id%></td>
      </tr>
    <% end %>
  </tbody>
</table><!-- Table End-->

app/views/students/admin.html.erb
<div class="user-details">
	<%= render 'user_details' %>
</div>
<div style="text-align: center; margin-top: 70px">
	<label style="font-family: monospace;font-size: xx-large;" class="user-name"></label><br>
</div>
<div class="student-details"></div>

<script type="text/javascript">
	$(document).ready(function() {
		$('#user_table').DataTable( {
			"searching": false,
			"paging": false,
			"lengthChange": false,
	 		"bInfo" : false,
	 		dom: 'Bfrtip',
	 		 buttons: 
      [
        {
          extend: 'excel',
          text: 'Download Excel',
          exportOptions: {
            columns: ":not(:last-child)"
          }
        }, 
        {
          extend: 'csv',
          text: 'Download CSV',
          exportOptions: {
            columns: ":not(:last-child)"
          }
        },
      ],
			"columnDefs": [ {
        "targets": -1,
        "data": null,
        render: function(data){
        	return '<button class="btn-view" name= '+data[0]+' type="button">View</button>';
        }
    	} ]
		});

		$(".btn-view").click(function(){
	    var user_id = $(this).attr('name')
	    $.ajax({
	      type: "GET",
	      url: "/get_student_by_user.js",
	      data: {user_id: user_id},
	      error: function(){alert("Sorry there was an error while loading the 'Student'. Please try refreshing the page.");}
	    });
  	});
	});
</script

app/views/students/get_student_by_user.js.erb
var user_name = "<%= @user.name%>"
$('.student-details').html("<%= escape_javascript render(:partial => 'student_records', :locals => { :student => @student}) %>");
$(".user-name").text(user_name + " Data")
$('#student_table').DataTable({
	"searching": false,
	"lengthChange": false,
	"bInfo" : false,
		dom: 'Bfrtip',
	buttons: 
	[
	  {
	    extend: 'excel',
	    text: 'Download Excel',
	    exportOptions: {
	      columns: ':not(.select-checkbox)'
	    }
	  }, 
	  {
	    extend: 'csv',
	    text: 'Download CSV',
	    exportOptions: {
	      columns: ':not(.select-checkbox)'
	    }
	  },
	],
	columnDefs: 
  [ 
    {
      orderable: false,
      className: 'select-checkbox',
      visible: false,
      targets:   0,
      value: 0
    } 
  ],
});

app/views/students/index.html.erb
<%= render 'form', student: @student, modal: false %>
<div id="student_modal_show">
  <%= render 'add_student_form_modal', student: @student %>
</div><br>
<label style="text-align: center;width: 924px;font-family: monospace;font-size: xx-large;">Historical Data</label><br>
<%= render 'student_records', students: @students %>
<br>

<script>
  jQuery.extend(jQuery.validator.messages, {
    required: "Mandatory Field",
  });
  $(document).ready(function() {

    $('#student_table').DataTable( {
      dom: 'Bfrtip', 
      "drawCallback": function(settings) {
        loadselectcheckbox();
      },
      "bFilter": false,
      buttons: 
      [
        {
          extend: 'excel',
          text: 'Download Excel',
          exportOptions: {
            columns: ':not(.select-checkbox)'
          }
        }, 
        {
          extend: 'csv',
          text: 'Download CSV',
          exportOptions: {
            columns: ':not(.select-checkbox)'
          }
        },
      ],
      columnDefs: 
      [ 
        {
          orderable: false,
          className: 'select-checkbox',
          targets:   0,
          value: 0
        } 
      ],
      columns: 
      [
        {defaultContent: ""},
        {data: 'id'},
         {
            data: 'created_at',
            type: 'date',
            render: function (data, type, row) {  return data.substr(0, 10); } //{return data ? moment(data).format('MM/DD/YY') : '';}
        },
        {data: 'name'},
        {data: 'student_class'},
        {data: 'phone'},
        {data: 'address'}
      ],
      select: {
        style:    'os',
          selector: 'td:first-child'
      },
      order: [[ 0, 'asc' ]]
    });
  });

  $(document).ready(function() {
    $("#loginForm").validate({
      rules:{
        'student[phone]':{
          digits: true,
          minlength:10,
          maxlength:10,
        }
      },
      messages:{
        'student[phone]':"Invalid Mobile Number"
      },
      submitHandler: function(form) {
        $.ajax({
          type: "POST",
          url : "/students.json",
          data: $("#loginForm").serialize(), // serializes the form's elements.
          success: function(data)
          {
          if (data["status"] == "false"){
            $('.notice').fadeIn().html($('<p class="alert alert-danger"> '+data.errors[0]+'</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
          }else{
            $('#loginForm')[0].reset();
            $('.notice').fadeIn().html($('<p class="alert alert-success">Student was successfully created.</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
            $('#student_table').DataTable().ajax.reload();}
          },
          error: function(data){
            $('.notice').fadeIn().html($('<p class="alert alert-danger">Something Went Wrong While Saving New Student Record.</p></div>').fadeIn());setTimeout(function(){ $('.notice').fadeOut(); }, 3000);
          }
        }); //ajax end
      } //submit handler end
    }); //form end
  });//ready function end

  function loadselectcheckbox() {
    $(".select-checkbox").click(function (){
      if (!$(this).parent().eq(0).hasClass("selected")) {
        var id = $(this).next().eq(0).html();
        $.ajax({
          type: "GET",
          url: '/students/'+id+ ".js"
        })  
      }
    })
  };
</script>

app/views/students/show.js.erb
$('#student_modal_show').html("<%= escape_javascript render(:partial => 'add_student_form_modal', :locals => { :student => @student, current_user: @current_user }) %>");
$("#add_student_form_modal_header").modal('show')

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>